import test from 'node:test';
import assert from 'node:assert/strict';
const M=await import('../model.mjs').catch(()=>({}));
test('默认演示数据包含可检查与重置的限制用量',()=>{const key=M.createSeed().keys.find(key=>key.id==='key-prod');assert.ok(key.limit>0);assert.ok(key.rate5h>0);assert.ok(key.usage5h>0);});
test('密钥保存白黑名单和三个额度窗口，拒绝负值',()=>{const s=M.createSeed(),f={name:'验证密钥',routeId:'gpt-pro',ipWhitelist:'192.0.2.1',ipBlacklist:'198.51.100.1',rate5h:10,rate1d:20,rate7d:30};const k=M.createKey(s,f);assert.equal(k.ipWhitelist,'192.0.2.1');assert.equal(k.ipBlacklist,'198.51.100.1');assert.deepEqual([k.rate5h,k.rate1d,k.rate7d],[10,20,30]);assert.throws(()=>M.createKey(s,{...f,rate5h:-1}),/额度/);});
test('同一线路多把密钥只计一条线路，删除最后一把才移出列表',()=>{
 assert.equal(typeof M.createSeed,'function');const s=M.createSeed();const before=M.configured(s,'Codex');const k=M.createKey(s,{routeId:'gpt-pro',name:'追加'});assert.equal(M.configured(s,'Codex'),before);M.deleteKey(s,k.id);assert.equal(M.configured(s,'Codex'),before);for(const k of [...s.keys].filter(k=>k.routeId==='gpt-pro'))M.deleteKey(s,k.id);assert.equal(M.configured(s,'Codex'),before-1);
});
test('创建校验拒绝空名称、停用线路和负额度；失败不修改数据',()=>{const s=M.createSeed(),count=s.keys.length;assert.throws(()=>M.createKey(s,{routeId:'gpt-pro',name:' '}));assert.throws(()=>M.createKey(s,{routeId:'deepseek',name:'test'}));assert.throws(()=>M.createKey(s,{routeId:'gpt-pro',name:'test',limit:-1}));assert.equal(s.keys.length,count);});
test('编辑密钥可以更换到管理正常线路，且不改写历史使用记录',()=>{const s=M.createSeed(),old=JSON.stringify(s.usage),key=s.keys.find(k=>k.id==='key-prod');M.editKey(s,'key-prod',{routeId:'gpt-economy',name:'新的名称',limit:0});assert.equal(key.name,'新的名称');assert.equal(key.routeId,'gpt-economy');assert.equal(JSON.stringify(s.usage),old);assert.throws(()=>M.editKey(s,'key-prod',{routeId:'deepseek',name:'新的名称',limit:0}),/管理正常/);assert.equal(key.routeId,'gpt-economy');});
test('线路质量排序优先可用线路，再比较成功率、延迟和倍率',()=>{const s=M.createSeed();const routes=M.sortRoutesByQuality(s.routes.filter(r=>r.tool==='Codex'));assert.deepEqual(routes.map(r=>r.id),['gpt-pro','gpt-economy','gpt-fast']);assert.equal(M.bestRoute(routes).id,'gpt-pro');const unavailable=M.sortRoutesByQuality(s.routes.filter(r=>r.tool==='Claude Code'));assert.equal(unavailable[0].id,'claude-standard');});
test('工具卡片按实际密钥数统计关联数量，且不会因线路已关联而禁用入口',()=>{const s=M.createSeed();assert.equal(M.linkedKeyCount(s,'Codex'),2);assert.equal(M.linkedKeyCount(s,'DeepSeek'),1);assert.deepEqual(M.toolButton(s,'Codex'),{label:'关联密钥',disabled:false});M.createKey(s,{routeId:'gpt-economy',name:'2'});M.createKey(s,{routeId:'gpt-fast',name:'3'});assert.equal(M.linkedKeyCount(s,'Codex'),4);assert.deepEqual(M.toolButton(s,'Codex'),{label:'关联密钥',disabled:false});});
test('充值额度允许 $1，拒绝低于 $1 的金额',()=>{const s=M.createSeed(),count=s.orders.length;const order=M.createOrder(s,1);assert.equal(order.amount,1);assert.equal(s.orders.length,count+1);assert.throws(()=>M.createOrder(s,.99),/1–10,000/);assert.equal(s.orders.length,count+1);});
test('支付仅在待支付订单成功后入账一次，关闭订单不能支付',()=>{const s=M.createSeed(),b=s.balance;const o=M.createOrder(s,30);assert.equal(s.balance,b);M.settleOrder(s,o.id,'paid');assert.equal(s.balance,b+30);M.settleOrder(s,o.id,'paid');assert.equal(s.balance,b+30);const c=M.createOrder(s,10);M.settleOrder(s,c.id,'closed');assert.throws(()=>M.settleOrder(s,c.id,'paid'));assert.equal(s.balance,b+30);});
test('兑换不区分大小写，重复与无效码不增加权益',()=>{const s=M.createSeed(),b=s.balance;M.redeem(s,' demo30 ');assert.equal(s.balance,b+30);assert.throws(()=>M.redeem(s,'DEMO30'));assert.throws(()=>M.redeem(s,'xxx'));assert.equal(s.balance,b+30);M.redeem(s,'PLUS2');assert.equal(s.concurrency,7);});
test('筛选与合计源于同一明细集合；零结果不伪造统计',()=>{const s=M.createSeed();const rows=M.filterUsage(s,{route:'gpt-pro',hours:24});assert.ok(rows.length>0);assert.ok(rows.every(r=>r.routeId==='gpt-pro'));const a=M.summarize(rows);assert.equal(a.requests,rows.length);assert.equal(a.tokens,rows.reduce((n,r)=>n+r.input+r.output+r.cache,0));assert.equal(M.summarize([]).latency,null);assert.equal(M.filterUsage(s,{model:'不存在'}).length,0);});
test('线路种子分别提供首字 P50、耗时 P50 和本次检查耗时',()=>{const s=M.createSeed(),r=s.routes.find(r=>r.id==='gpt-pro');assert.equal(typeof r.p50,'number');assert.equal(typeof r.durationP50,'number');assert.notEqual(r.durationP50,r.p50);assert.equal(M.checkResult(r).text,r.checkLatency.toFixed(2)+'s');});
test('线路检查准确区分失败、超时和管理员停用',()=>{const s=M.createSeed();assert.equal(M.checkResult(s.routes.find(r=>r.id==='deepseek')).text,'线路已停用');assert.equal(M.checkResult(s.routes.find(r=>r.id==='claude-standard')).text,'检查失败');assert.equal(M.checkResult(s.routes.find(r=>r.id==='grok-discount')).text,'响应超时');});
test('线路状态由管理状态和最近检查结果共同决定',()=>{const s=M.createSeed();assert.deepEqual(M.lineStatus(s.routes.find(r=>r.id==='gpt-pro')),{text:'可用',kind:'success'});assert.deepEqual(M.lineStatus(s.routes.find(r=>r.id==='claude-standard')),{text:'不可用',kind:'danger'});assert.deepEqual(M.lineStatus(s.routes.find(r=>r.id==='deepseek')),{text:'停用',kind:'muted'});});
test('成功率按统一阈值分色，无样本不判定',()=>{
 for(const [rate,tone] of [[100,'high'],[80,'high'],[79,'medium'],[50,'medium'],[49,'low'],[0,'low'],[null,'unknown']])assert.equal(M.successRateTone(rate),tone,String(rate));
});
test('字段中的逗号、引号、换行和公式导出为安全 CSV',()=>{const csv=M.toCsv(['名称'],[['=1+1'],['a,"b"\nc']]);assert.ok(csv.includes("'=1+1"));assert.ok(csv.includes('"a,""b""\nc"'));});
test('站内检查更新线路统计与可用性，不扣账户余额或创建个人消费记录',()=>{const s=M.createSeed();const r=s.routes.find(r=>r.id==='claude-standard'),disabled=s.routes.find(r=>r.id==='deepseek'),total=r.total,balance=s.balance,usage=s.usage.length;assert.equal(typeof M.applyLineChecks,'function');M.applyLineChecks(s);assert.equal(r.total,total+1);assert.equal(r.available,false);assert.equal(disabled.total,0);assert.equal(s.balance,balance);assert.equal(s.usage.length,usage);});
