import * as M from './model.mjs';
import {esc,money,rmb,date,routeIdentity,btn,iconBtn,select,field,empty,errorBox,formActions,showModal,closeModal,formError,toast,copy,table} from './ui.mjs';
import {keyHeaders,usageHeaders,usageErrorHeaders} from './pages.mjs';
import {defaultHiddenKeyColumns} from './key-columns.mjs';
const at=id=>`data-id="${esc(id)}"`;
const input=(name,value='',attrs='')=>`<input name="${name}" value="${esc(value)}" ${attrs}>`;
const toggle=(id,label,checked,body)=>`<label class="toggle-row"><span>${label}</span><input type="checkbox" class="switch" name="${id}" ${checked?'checked':''} data-toggle="${id}-detail"></label><div class="toggle-detail" id="${id}-detail" ${checked?'':'hidden'}>${body}</div>`;
export const routeChoice=r=>routeIdentity(r,'route-choice-identity');
const keyOption=(id,label,checked,body)=>`<div class="key-option">${toggle(id,label,checked,body)}</div>`;
export function keyFormContent(c,{tool='',id='',routeId=''}={}){
 const k=id?c.state.keys.find(key=>key.id===id):null;
 const routes=c.state.routes.filter(r=>(r.enabled||r.id===k?.routeId)&&(!tool||r.tool===tool));
 const selected=k?.routeId||routeId,route=c.state.routes.find(r=>r.id===selected);
 const nameField=field('名称',input('name',k?.name||'','placeholder="我的 API 密钥" maxlength="50" required'));
 const routeField=`<div class="field route-select"><label class="label" id="route-label">线路</label><input type="hidden" name="routeId" value="${esc(selected)}"><button type="button" class="select-trigger" data-action="route-dropdown" aria-labelledby="route-label route-value" aria-expanded="false" aria-required="true"><span id="route-value">${routeChoice(route)}</span><span aria-hidden="true">⌄</span></button><span class="field-error" id="route-error" role="alert"></span><div id="route-options" class="route-options" hidden><input type="search" placeholder="搜索${tool?'当前工具':''}线路" aria-label="搜索线路" data-input="route-search"><div id="route-option-list">${routeOptions(c,routes,selected)}</div></div></div>`;
 const ipFields=field('IP 白名单',`<textarea name="ipWhitelist" rows="2" placeholder="每行一个 IP 或网段">${esc(k?.ipWhitelist||'')}</textarea>`)+field('IP 黑名单',`<textarea name="ipBlacklist" rows="2" placeholder="每行一个 IP 或网段">${esc(k?.ipBlacklist||'')}</textarea>`);
 const rateFields=[['rate5h','5 小时额度'],['rate1d','1 天额度'],['rate7d','7 天额度']].map(([name,label])=>field(label,input(name,k?.[name]||0,'type="number" min="0" step="0.01"'))).join('');
 const expiry=`<div class="expiry-presets">${[7,30,90].map(days=>btn(`${days} 天`,'key-expires-preset','small',`data-days="${days}"`)).join('')}</div>${input('expires',k?.expires||'','type="date"')}`;
 return `<form id="key-form" class="compact-key-form"><div class="modal-body"><div class="key-form-stack">${nameField}${routeField}</div><div class="key-settings-stack">${k?'':keyOption('customOn','自定义密钥',false,input('custom','','placeholder="8–100 位字母、数字、下划线或横线" autocomplete="off"'))}${keyOption('ipOn','IP 限制',!!(k?.ipWhitelist||k?.ipBlacklist),ipFields)}<div class="key-limit-option">${field('额度限制',input('limit',k?.limit??0,'type="number" min="0" step="0.01" placeholder="输入 USD 额度限制"'),'设置此密钥可消费的最大金额。0 = 无限制。')}</div>${keyOption('rateOn','速率限制',!!(k?.rate5h||k?.rate1d||k?.rate7d),rateFields)}${keyOption('expiresOn','密钥有效期',!!k?.expires,expiry)}</div>${errorBox()}</div>${formActions(k?'保存':'创建')}</form>`;
}
export function openKey(c,options={}){const {tool='',id='',returnTo=null}=options;c.modal={type:'key',id,tool,returnTo};showModal(id?'编辑密钥':tool?'创建线路密钥':'创建密钥',keyFormContent(c,options));document.querySelector('#modal')?.classList.add('key-form-modal');}
export function routeOptions(c,routes,selected=''){return routes.map(r=>{const linked=c.state.keys.filter(k=>k.routeId===r.id).length,status=M.lineStatus(r),success=r.success==null?'—':r.success+'%';return `<button type="button" class="route-option" data-action="choose-route" data-id="${r.id}" aria-selected="${r.id===selected}"><span class="row route-option-main">${routeChoice(r)}<span class="push route-option-state"><span class="dot ${status.kind}"></span>${status.text} · 关联密钥 ${linked} 把</span></span><small>近 1 小时稳定性 <span class="rate-${M.successRateTone(r.success)}">${success}</span> · 首字 ${r.p50?.toFixed(2)||'—'}s</small></button>`;}).join('')||empty('暂无可配置线路');}
export function routeDetailsContent(c,tool){const routes=M.sortRoutesByQuality(c.state.routes.filter(r=>r.tool===tool)),best=M.bestRoute(routes),hours=c.detailHours||1;const window={1:{success:1,requests:1,latency:1},24:{success:.985,requests:4.8,latency:1.06},168:{success:.965,requests:16.2,latency:1.12}}[hours]||{success:1,requests:1,latency:1};const successOf=r=>r.success==null?null:Math.max(0,Math.min(100,Math.round(r.success*window.success))),requestsOf=r=>Math.round((r.total??0)*window.requests),firstP50=r=>r.p50==null?'—':(r.p50*window.latency).toFixed(2)+'s',durationP50=r=>{const base=r.durationP50??(r.p50==null?null:r.p50*2.65);return base==null?'—':(base*window.latency).toFixed(2)+'s'},period=`<div class="detail-period"><span>统计范围</span><div class="detail-period-segment" role="group" aria-label="线路统计时间">${[[1,'近 1 小时'],[24,'近 24 小时'],[168,'近 7 天']].map(([value,label])=>btn(label,'detail-hours',hours===value?'active':'',`data-hours="${value}" aria-pressed="${hours===value}"`)).join('')}</div></div>`;return `<div class="modal-body route-details-body"><div class="detail-section-head"><p>已按线路质量从高到低排列；成功率、请求次数与 P50 按所选时间范围统计</p>${period}</div>${table(['线路','关联密钥','成功率','请求次数','首字 P50','耗时 P50','本次检查'],routes.map(r=>{const check=M.checkResult(r),status=M.lineStatus(r),success=successOf(r),linked=c.state.keys.filter(k=>k.routeId===r.id).length,linkedAction=r.enabled?btn('关联密钥','detail-create','small',`data-tool="${esc(tool)}" ${at(r.id)}`):'<span class="muted">不可配置</span>';return [`<div class="detail-route"><div class="detail-route-title">${routeIdentity(r,'route-choice-identity')}${r.id===best?.id?'<span class="best-route-badge">最佳线路</span>':''}</div><small class="route-availability ${status.kind}"><span class="dot ${status.kind}"></span>${status.text}</small></div>`,`<div class="linked-key-cell" aria-label="关联密钥单元格"><span>${linked?`已关联 · ${linked} 把`:'未关联 · 0 把'}</span>${linkedAction}</div>`,success==null?'<span class="muted">—</span>':`<strong class="success-rate data rate-${M.successRateTone(success)}">${success}%</strong>`,`<span class="request-count data">${requestsOf(r)}</span>`, `<strong class="latency-metric data">${firstP50(r)}</strong>`,`<strong class="latency-metric data">${durationP50(r)}</strong>`,`<span class="${check.kind}">${check.kind==='success'?'<span aria-label="成功">✓ </span>':''}${check.text}</span>`] }),'detail-table route-metrics-table')}${routes.length?'':empty('暂无线路')}</div>`;}
export function details(c,tool){c.modal={type:'details',tool};showModal(tool+' 线路详情',routeDetailsContent(c,tool),true);document.querySelector('#modal')?.classList.add('route-details-modal');queueMicrotask(()=>document.querySelector('#modal .close-btn')?.focus({preventScroll:true}));}
export function closeDialog(c){const returnTo=c.modal?.returnTo;if(returnTo?.type==='details')return details(c,returnTo.tool);closeModal();c.modal=null;}
export function confirmKey(c,id,action){const k=c.state.keys.find(k=>k.id===id);if(!k)return;c.modal={type:'confirm-key',id,action};showModal(action==='delete'?'删除密钥':k.enabled?'禁用密钥':'启用密钥',`<form id="confirm-key-form"><div class="modal-body"><p>确定${action==='delete'?'删除':k.enabled?'禁用':'启用'}「${esc(k.name)}」？</p><p class="hint">${action==='delete'?'删除后，此密钥将从列表移除；历史使用记录保留。':k.enabled?'禁用后，此密钥不能继续访问线路。':'启用后恢复此密钥的可用状态。'}</p>${errorBox()}</div><footer class="modal-actions">${btn('取消','close')}<button type="submit" class="${action==='delete'?'danger-primary':'primary'}">确认${action==='delete'?'删除':k.enabled?'禁用':'启用'}</button></footer></form>`);}
export function resetKeyUsageContent(k,kind){const label=kind==='quota'?'额度':'速率';return `<form id="reset-key-usage-form"><div class="modal-body"><p>确认重置${label}用量「${esc(k.name)}」？</p><p class="hint">仅清除当前限制的用量计数，不更改限制值或历史使用记录。</p>${errorBox()}</div><footer class="modal-actions">${btn('取消','close')}<button type="submit" class="primary">确认重置</button></footer></form>`;}
export function resetKeyUsage(c,id,kind){const k=c.state.keys.find(key=>key.id===id);if(!k)return;c.modal={type:'reset-key-usage',id,kind};showModal(kind==='quota'?'重置额度用量':'重置速率用量',resetKeyUsageContent(k,kind));}
export function columns(c,kind){if(!c.state.columns[kind])c.state.columns[kind]=kind==='keys'?[...defaultHiddenKeyColumns]:kind==='usageErrors'?[8]:[];c.modal={type:'columns',kind};const headers=kind==='keys'?keyHeaders:kind==='usageErrors'?usageErrorHeaders:usageHeaders;showModal('列设置',`<form id="columns-form"><div class="modal-body"><div class="column-list">${headers.map((h,i)=>`<label><input type="checkbox" name="column" value="${i}" ${c.state.columns[kind].includes(i)?'':'checked'} ${kind==='keys'&&[0,6].includes(i)?'disabled':''}>${h}</label>`).join('')}</div><div style="margin-top:24px">${btn('恢复默认列','columns-reset','ghost')}</div>${errorBox()}</div>${formActions('应用')}</form>`);}
const orderLabel=status=>({pending:'待支付',paid:'已完成',completed:'已完成',closed:'已取消',cancelled:'已取消',expired:'已过期',failed:'失败',refunded:'已退款'}[String(status||'').toLowerCase()]||String(status||'未知状态'));
export function confirmOrderCancel(c,id){const o=c.state.orders.find(o=>o.id===id);if(!o||String(o.status).toLowerCase()!=='pending')return toast('订单状态已更新，无需取消',true);c.modal={type:'cancel-order',id};showModal('取消待支付订单',`<form id="cancel-order-form"><div class="modal-body"><p>确定取消订单「${esc(o.number)}」？</p><dl class="kv"><dt>支付金额</dt><dd>${rmb(o.amount)}</dd><dt>支付方式</dt><dd>${esc(o.method||'—')}</dd></dl><p class="hint">取消后当前支付承接会结束；如需充值，请重新创建订单。</p>${errorBox()}</div><footer class="modal-actions">${btn('继续支付','close')}<button type="submit" class="danger-primary">确认取消订单</button></footer></form>`);}
export function orderDetail(c,id){const o=c.state.orders.find(o=>o.id===id);if(!o)return;const pending=String(o.status).toLowerCase()==='pending',completed=['paid','completed'].includes(String(o.status).toLowerCase());c.modal={type:'order-detail',id};showModal('订单详情',`<div class="modal-body"><dl class="kv">${[['订单编号',o.number],['支付状态',orderLabel(o.status)],['充值额度',money(o.amount)],['获得总额度',money(completed?o.credit:0)],['实际支付金额',rmb(o.amount)],['支付方式',o.method||'—'],['创建时间',date(o.created)]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${pending?'<p class="notice">该订单仍在等待支付。生产环境会继续轮询状态，并允许在有效期内恢复支付承接。</p>':''}</div><footer class="modal-actions">${pending?btn('取消订单','cancel-order','ghost danger',at(o.id)):''}${btn('关闭','close',pending?'':'primary')}</footer>`);}
export function profileDialog(c,kind){const p=c.state.profile;c.modal={type:'profile',kind,sentTo:''};const titles={name:'编辑用户名',email:'管理邮箱',password:p.passwordSet?'修改密码':'设置密码'},newPassword=field('新密码','<input name="password" type="password" minlength="8" required autocomplete="new-password">')+field('确认新密码','<input name="confirm" type="password" minlength="8" required autocomplete="new-password">'),firstSetEmail=String(p.email||'').endsWith('.invalid')?'':p.email;const content=kind==='name'?field('用户名',input('name',p.name,'maxlength="30" required autofocus')):kind==='email'?field('新邮箱',input('email','','type="email" placeholder="输入新邮箱" required autocomplete="off"'))+`<div class="row">${field('邮箱验证码',input('code','','placeholder="输入验证码" pattern="[0-9]{6}" required'))}${btn('发送验证码','send-code','','style="margin-top:4px"')}</div>`+field('身份验证信息',input('verify','','placeholder="演示验证信息：DEMO" required')):p.passwordSet?field('当前密码','<input name="currentPassword" type="password" required autocomplete="current-password">')+newPassword:field('登录邮箱',input('email',firstSetEmail,'type="email" placeholder="输入可接收验证码的邮箱" required autocomplete="email"'))+`<div class="row">${field('邮箱验证码',input('code','','placeholder="输入验证码" pattern="[0-9]{6}" required'))}${btn('发送验证码','send-code','','style="margin-top:4px"')}</div>`+newPassword;showModal(titles[kind],`<form id="profile-form"><div class="modal-body">${content}${errorBox()}</div>${formActions(kind==='email'?'更换主邮箱':'保存')}</form>`);}
export function security(c,kind){c.modal={type:'security',kind};const p=c.state.profile;if(kind==='passkey')showModal('Passkey',`<form id="security-form"><div class="modal-body"><p class="notice">仅模拟设备凭证管理，不调用真实设备认证。</p>${p.passkeys.length?table(['设备','添加时间','操作'],p.passkeys.map(k=>[esc(k.name),date(k.created),btn('移除','remove-passkey','text-btn danger',at(k.id))])):''}${field('设备名称',input('device','','placeholder="例如：我的 MacBook" maxlength="50" required'))}${errorBox()}</div>${formActions('添加演示凭证')}</form>`);else showModal('两步验证',`<form id="security-form"><div class="modal-body"><p class="notice">交互演示：输入演示验证码 123456，不会更改真实账号。</p>${field('验证码',input('code','','inputmode="numeric" pattern="[0-9]{6}" required'))}${errorBox()}</div>${formActions(p.twoFactor?'关闭两步验证':'启用两步验证')}</form>`);}
export function support(c){c.modal={type:'support'};const contactInfo=String(c.state.contactInfo||'').trim();showModal('联系星桥客服',`<div class="modal-body support-dialog-body"><div class="support-qr"><img src="./assets/qq-group-1080152144.png" alt="星桥客服 QQ 群二维码"></div><p class="support-scan-hint">使用 QQ 扫码加入群聊</p><div class="support-group-row"><div class="support-group-meta"><span>QQ 群</span><strong class="data">1080152144</strong></div>${btn('复制群号','copy-support-group','primary','aria-label="复制 QQ 群号 1080152144"')}</div><div class="support-contact-info"><span>其他联系方式</span><p class="${contactInfo?'':'muted'}">${contactInfo?esc(contactInfo):'暂未配置其他联系方式'}</p></div></div><footer class="modal-actions">${btn('关闭','close')}</footer>`);}
export function useKey(c,id){const k=c.state.keys.find(k=>k.id===id);c.modal={type:'use',id};showModal(k?'使用密钥':'接入说明',`<div class="modal-body"><p class="secondary">${k?esc(k.name)+' · '+esc(c.state.routes.find(r=>r.id===k.routeId)?.name):'在 AI 工具页选择线路并创建密钥后，可以在此复制连接信息。'}</p><div class="copy-row"><code>${M.endpoint}</code>${btn('复制地址','copy-endpoint')}</div>${k?`<div class="copy-row"><code>${esc(k.token)}</code>${btn('复制密钥','copy-key','',at(k.id))}</div>`:''}<p class="notice">当前地址与密钥均为无效演示数据，用于体验复制与配置操作，不可连接真实 AI 服务。</p></div><footer class="modal-actions">${btn('关闭','close')}</footer>`);}
export function importKeyContent(k){return `<div class="modal-body"><dl class="kv"><dt>密钥名称</dt><dd>${esc(k.name)}</dd><dt>API 端点</dt><dd><code>${M.endpoint}</code></dd><dt>密钥</dt><dd><code>demo-••••${esc(k.token.slice(-4))}</code></dd></dl><p class="notice">此原型使用无效演示数据。外部应用 CC Switch 不会自动打开，也不会自动写入外部应用；请在真实站点完成导入。</p></div><footer class="modal-actions">${btn('关闭','close')}</footer>`;}
export function importKey(c,id){const k=c.state.keys.find(key=>key.id===id);if(!k)return;c.modal={type:'import',id};showModal('导入到 CCS',importKeyContent(k));}
export function demo(c){c.modal={type:'demo'};showModal('交互体验设置',`<div class="modal-body"><p class="secondary">六个业务页面使用同一份本地模拟数据，刷新后保留。不会连接真实支付、邮箱、CCS 或后台。</p><div class="notice">兑换码 DEMO30：增加 $30.00 额度<br>兑换码 PLUS2：增加 2 路并发<br>邮箱验证码：123456；身份验证：DEMO</div><div class="review-grid">${btn('恢复初始示例数据','reset-demo')}${btn('体验首次使用（无密钥）','empty-demo')}${btn('下一次创建失败','fail-create')}${btn('下一次订单创建失败','fail-payment')}${btn('线路统计读取失败','fail-stats')}${btn('使用统计加载失败','fail-usage-stats')}${btn('使用明细加载失败','fail-usage-list')}${btn('下一次地区查询失败','fail-geo')}${btn('下一次 CSV 导出失败','fail-export')}</div><p class="footnote">错误演示保留仍可用的工作面；刷新、重试或重新筛选后恢复。支付终态不放在普通用户流程中模拟。</p></div><footer class="modal-actions">${btn('关闭','close')}</footer>`);}
export function requestDetail(c,id){const r=c.state.usage.find(r=>r.id===id);showModal('请求详情',`<div class="modal-body"><dl class="kv">${[['请求 ID',r.id],['API 密钥',r.keyName],['模型',r.model],['线路',r.routeName],['端点',r.endpoint],['Token',`输入 ${r.input} / 输出 ${r.output} / 缓存 ${r.cache}`],['实际消费',money(r.cost)],['标准价',money(r.standard)],['延迟',r.latency+'s'],['类型',M.usageTypeLabels[r.type]||r.type],['计费类型',r.billingType==='1'?'订阅套餐':'钱包余额'],['计费模式',M.usageModeLabels[r.mode]||r.mode],['时间',date(r.time)]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl></div><footer class="modal-actions">${btn('关闭','close')}</footer>`);}
export async function submitDialog(c,form){const f=Object.fromEntries(new FormData(form));try{
 if(form.id==='key-form'){if(!f.routeId)throw Error('请选择线路');const fields={...f,custom:f.customOn?f.custom:'',ipWhitelist:f.ipOn?f.ipWhitelist:'',ipBlacklist:f.ipOn?f.ipBlacklist:'',rate5h:f.rateOn?f.rate5h:0,rate1d:f.rateOn?f.rate1d:0,rate7d:f.rateOn?f.rate7d:0,expires:f.expiresOn?f.expires:''};if(f.customOn&&!f.custom.trim())throw Error('请输入自定义密钥');if(f.expiresOn&&!f.expires)throw Error('请选择有效期');if(c.failCreate){c.failCreate=false;throw Error('创建失败：模拟网络异常。输入已保留，请重试。');}const submit=form.querySelector('[type=submit]');submit.disabled=true;submit.textContent=c.modal.id?'保存中…':'创建中…';await new Promise(r=>setTimeout(r,350));if(!form.isConnected)return;const edited=!!c.modal.id;edited?M.editKey(c.state,c.modal.id,fields):M.createKey(c.state,fields);c.save();closeModal();c.render();toast(edited?'密钥已更新':'密钥已创建');}
 else if(form.id==='confirm-key-form'){const {id,action}=c.modal;if(action==='delete')M.deleteKey(c.state,id);else{const k=c.state.keys.find(k=>k.id===id);k.enabled=!k.enabled;k.concurrency=0;}c.save();closeModal();c.render();toast(action==='delete'?'密钥已删除':'密钥状态已更新');}
 else if(form.id==='reset-key-usage-form'){const {id,kind}=c.modal,k=c.state.keys.find(key=>key.id===id);if(!k)throw Error('密钥不存在');if(kind==='quota')k.quotaResetAt=Date.now();else if(kind==='rate'){k.usage5h=0;k.usage1d=0;k.usage7d=0;}else throw Error('未知重置类型');c.save();closeModal();c.render();toast('用量计数已重置（仅本地演示）');}
 else if(form.id==='cancel-order-form'){const {id}=c.modal;const o=c.state.orders.find(o=>o.id===id);if(!o||String(o.status).toLowerCase()!=='pending')throw Error('订单状态已更新，不能重复取消');M.settleOrder(c.state,id,'closed');if(c.state.paymentRecovery?.orderId===id)delete c.state.paymentRecovery;if(c.paymentFlow?.orderId===id)c.paymentFlow=null;c.paymentError='';c.save();closeModal();c.modal=null;c.render();toast('订单已取消');}
 else if(form.id==='columns-form'){const checked=[...form.querySelectorAll('[name=column]:checked')].map(e=>Number(e.value));if(c.modal.kind==='keys')checked.push(0,6);if(!checked.length)throw Error('请至少保留一列');const headers=c.modal.kind==='keys'?keyHeaders:c.modal.kind==='usageErrors'?usageErrorHeaders:usageHeaders;c.state.columns[c.modal.kind]=headers.map((_,i)=>i).filter(i=>!checked.includes(i));c.save();closeModal();c.render();}
 else if(form.id==='profile-form'){const p=c.state.profile,kind=c.modal.kind;if(kind==='name'){if(!f.name.trim())throw Error('请输入用户名');p.name=f.name.trim();}else if(kind==='email'){if(c.modal.sentTo!==f.email.trim())throw Error('请先向当前填写的新邮箱发送演示验证码');if(f.code!=='123456'||f.verify!=='DEMO')throw Error('验证码或身份验证信息不正确');p.email=f.email.trim();}else{if(p.passwordSet){if(f.currentPassword!=='current-password')throw Error('当前密码不正确');}else{if(c.modal.sentTo!==f.email.trim())throw Error('请先向当前填写的登录邮箱发送验证码');if(f.code!=='123456')throw Error('邮箱验证码不正确');p.email=f.email.trim();}if(f.password!==f.confirm)throw Error('两次输入的密码不一致');p.passwordSet=true;}c.save();closeModal();c.render();toast('资料已更新（仅本地演示）');}
 else if(form.id==='security-form'){if(c.modal.kind==='passkey'){if(!f.device.trim())throw Error('请输入设备名称');c.state.profile.passkeys.push({id:M.uid(),name:f.device.trim(),created:Date.now()});}else{if(f.code!=='123456')throw Error('验证码不正确');c.state.profile.twoFactor=!c.state.profile.twoFactor;}c.save();closeModal();c.render();toast('安全状态已更新（演示）');}

 }catch(e){if(form.id==='key-form'&&e.message==='请选择线路'){const trigger=form.querySelector('.select-trigger');const error=form.querySelector('#route-error');if(trigger)trigger.setAttribute('aria-invalid','true');if(error)error.textContent=e.message;trigger?.focus();}else formError(e.message);const b=form.querySelector('[type=submit]');if(b){b.disabled=false;if(form.id==='key-form')b.textContent=c.modal.id?'保存':'创建';}}
}
