import * as M from './model.mjs';
import {extraKeyHeaders,extraKeyCells} from './key-columns.mjs';
import {esc,money,rmb,num,compact,date,icon,providerLogo,routeIdentity,btn,iconBtn,select,dropdown,field,empty,requestError,table} from './ui.mjs';
export const keyHeaders=['名称','API 密钥','线路','当前并发','用量','过期时间','操作',...extraKeyHeaders];
export const usageHeaders=['API 密钥','模型','推理强度','端点','IP','线路','类型','计费模式','Token','费用','延迟','时间','详情'];
const attrs=id=>`data-id="${esc(id)}"`;
const toolProviders={Codex:'OpenAI','Claude Code':'Anthropic',Grok:'xAI',DeepSeek:'DeepSeek'};
export function shell(ctx){const s=ctx.state;return `<aside class="sidebar"><div class="brand"><img src="./assets/logo-brand.png" alt="星桥"><div><strong>星桥 AI Link</strong><small>v0.2.4</small></div></div><nav class="nav" aria-label="主导航">${[['ai','tools','AI 工具'],['usage','history','使用记录'],['keys','key','我的密钥']].map(([id,ico,label])=>btn(`${icon(ico)}<span>${label}</span>`,'navigate',ctx.page===id?'active':'',`data-page="${id}" aria-label="${label}" ${ctx.page===id?'aria-current="page"':''}`)).join('')}</nav><div class="sidebar-bottom"><div class="spacer"></div>${btn(`<strong class="data" data-balance>${money(s.balance)}</strong><span>充值｜兑换</span>`,'navigate','balance-entry','data-page="recharge" aria-label="充值与兑换"')}<div class="user-bar">${btn(`<span class="avatar">${s.profile.avatar?`<img src="${esc(s.profile.avatar)}" alt="">`:icon('user')}</span><span class="user-name">${esc(s.profile.name)}</span>`,'user-menu','user','aria-label="用户菜单" aria-expanded="false"')}${iconBtn('support','support','联系客服')}<div id="user-menu" class="user-menu" hidden>${btn('个人资料','navigate','','data-page="profile"')}${btn('我的密钥','navigate','','data-page="keys"')}${btn('退出登录','logout')}</div></div></div></aside><main class="main" id="main" tabindex="-1"><div class="content" id="content">${page(ctx)}</div></main><div class="preview-bar">${btn('交互演示 · 示例数据','demo','', 'aria-label="演示设置"')}</div>`;}
const pageMeta={
 ai:'请选择你的 AI 工具',
 usage:'使用记录',
 keys:'我的密钥',
 recharge:'充值与兑换',
 orders:'我的订单',
 profile:'个人资料'
};
export function page(c){const route=pageMeta[c.page]?c.page:'ai',title=pageMeta[route];return `<header class="page-head"><h1>${title}</h1></header>${({ai:aiPage,keys:keysPage,usage:usagePage,recharge:rechargePage,orders:ordersPage,profile:profilePage})[route](c)}`;}
function aiPage(c){
 const s=c.state;
 return `<section aria-label="AI 工具"><div class="tool-grid">${M.tools.map(tool=>{
  const all=s.routes.filter(r=>r.tool===tool&&r.enabled),available=all.filter(r=>M.lineStatus(r).kind==='success'),best=available[0],b=M.toolButton(s,tool),statusKind=!all.length?'muted':available.length?'success':'danger',statusText=!all.length?'暂无可用线路':available.length?`可用 · ${available.length}/${all.length} 条`:`不可用 · 0/${all.length} 条`;
  return `<article class="tool-card" data-tool="${esc(tool)}"><h3 class="tool-title">${providerLogo(toolProviders[tool])}<span>${esc(tool)}</span></h3><span class="tool-type">${tool==='Codex'||tool==='Claude Code'?'AI 编程':'通用 AI'}</span><div class="tool-status status-${statusKind}"><span class="dot ${statusKind}"></span><span class="availability-pill">${statusText}</span>${iconBtn('info','route-details',tool+' 线路详情',`data-tool="${esc(tool)}"`)}</div><div class="separator"></div><small>最佳线路</small><strong class="best ${!best?'muted':''}">${best?.name||'暂无可用线路'}</strong><div class="card-bottom"><span>已关联 ${M.linkedKeyCount(s,tool)} 把密钥</span>${btn(b.label,'create-key','small',`data-tool="${esc(tool)}" ${b.disabled?'disabled':''}`)}</div></article>`;
 }).join('')}</div><section class="panel lines-panel"><div class="panel-head"><h2>我的 AI 线路</h2>${iconBtn('refresh','check-lines','检查线路',c.checking?'disabled':'')}</div><div class="route-table"><div class="route-header"><span>线路</span><span>近 1 小时成功率</span><span>本次检查结果</span><span>关联密钥</span><span>操作</span></div><div class="route-scroll">${M.configuredRoutes(s).map(r=>{
  const count=s.keys.filter(k=>k.routeId===r.id).length,result=!r.enabled?{text:'线路已停用',kind:'muted'}:c.checking?{text:'检查中…',kind:'warning'}:c.checks[r.id]||{text:'—',kind:'muted'},lineStatus=M.lineStatus(r);
  return `<div class="route-row" data-route="${r.id}"><div class="route-name"><span class="dot line-status-dot ${lineStatus.kind}" title="${lineStatus.text}" aria-label="${lineStatus.text}"></span><div>${routeIdentity(r,'route-list-identity')}<small>${r.provider} · <span class="${lineStatus.kind}">${lineStatus.text}</span></small></div></div>${!r.enabled?'<span class="muted">—</span>':c.failStats?'<span class="danger">暂不可用</span>':r.total&&r.success!=null?btn(`${r.success}%`,'rate-detail',`rate rate-${M.successRateTone(r.success)}`,attrs(r.id)):'<span class="muted">近 1 小时无请求</span>'}<span class="metric ${result.kind}" ${result.text==='—'?'title="本次尚未检查"':''}>${result.kind==='success'?'<span aria-label="成功">✓ </span>':''}${result.text}</span><span class="secondary">${count} 把</span>${btn('查看关联密钥','related-keys','text-btn',attrs(r.id))}</div>`;
 }).join('')||empty('还没有配置线路',btn('创建密钥','create-key','primary'))}</div></div></section></section>`;
}
export function filteredKeys(c){const f=c.keyFilter;let keys=c.state.keys.filter(k=>(!f.search||(k.name+' '+k.token).toLowerCase().includes(f.search.toLowerCase()))&&(!f.route||k.routeId===f.route)&&(!f.status||M.keyStatus(k)===f.status));const [field,dir]=c.keySort;const lastUsed=new Map();if(field==='lastUsed')for(const row of c.state.usage)lastUsed.set(row.keyId,Math.max(lastUsed.get(row.keyId)||0,row.time));const value=k=>field==='expires'?(k.expires||'9999'):field==='lastUsed'?(lastUsed.get(k.id)||0):k[field];keys.sort((a,b)=>{const av=value(a),bv=value(b);return (typeof av==='number'?av-bv:String(av).localeCompare(String(bv),'zh'))*dir;});return keys;}
function keyRouteMenu(c,k){if(c.keyRouteOpen!==k.id)return '';const q=(c.keyRouteSearch||'').toLowerCase();const routes=M.sortRoutesByQuality(c.state.routes.filter(r=>(r.enabled||r.id===k.routeId)&&(r.name+' '+r.provider+' '+r.tool).toLowerCase().includes(q))),anchor=c.keyRouteAnchor||{},style=`--popover-left:${Number(anchor.left)||12}px;--popover-top:${Number(anchor.top)||12}px;--popover-width:${Number(anchor.width)||360}px;--popover-max-height:${Number(anchor.maxHeight)||310}px`;return `<div class="brand-dropdown-menu key-route-popover" style="${style}"><input type="search" aria-label="搜索线路" placeholder="搜索线路..." value="${esc(c.keyRouteSearch||'')}" data-input="key-route-search"><div class="key-route-options">${routes.map(r=>{const status=M.lineStatus(r),success=r.success==null?'—':r.success+'%',first=r.p50==null?'—':r.p50.toFixed(2)+'s';return `<button type="button" class="key-route-option" data-action="choose-key-route" data-id="${r.id}" data-key-id="${k.id}" aria-selected="${r.id===k.routeId}"><span class="key-route-option-main"><span>${routeIdentity(r)}</span><small class="key-route-quality">近 1 小时稳定性 <span class="rate-${M.successRateTone(r.success)}">${success}</span> · 首字 ${first}</small></span><small class="key-route-option-state"><span class="dot ${status.kind}"></span>${status.text}${r.id===k.routeId?' · 当前线路':''}</small></button>`;}).join('')||empty('没有匹配线路')}</div></div>`;}
function keysPage(c){
 const s=c.state,hidden=s.columns.keys||[],allRows=filteredKeys(c),pageSize=[10,20,50].includes(Number(c.keyPageSize))?Number(c.keyPageSize):20;
 const totalPages=Math.max(1,Math.ceil(allRows.length/pageSize)),currentPage=Math.min(Math.max(1,Number(c.keyPage)||1),totalPages),start=(currentPage-1)*pageSize,rows=allRows.slice(start,start+pageSize);
 c.keyPage=currentPage;c.keyPageSize=pageSize;
 const sortFields={0:'name',3:'concurrency',5:'expires',7:'id',11:'lastUsed',13:'created'};
 const headers=keyHeaders.map((h,i)=>sortFields[i]?btn(`${h} ${c.keySort[0]===sortFields[i]?(c.keySort[1]>0?'↑':'↓'):'↕'}`,'key-sort','sort',`data-field="${sortFields[i]}"`):h);
 const data=rows.map(k=>{
  const usage=s.usage.filter(r=>r.keyId===k.id),today=usage.filter(r=>r.time>Date.now()-86400000),status=M.keyStatus(k),route=s.routes.find(r=>r.id===k.routeId);
  return [
   `<strong>${esc(k.name)}</strong><span class="cell-sub ${status==='enabled'?'success':'muted'}">${{enabled:'启用',disabled:'已禁用',expired:'已过期'}[status]}</span>`,
   `<div class="secret"><code>demo-••••${esc(k.token.slice(-4))}</code>${btn('复制','copy-key','small',attrs(k.id))}</div>`,
   `<div class="brand-dropdown brand-dropdown-rich key-route-cell" data-dropdown>${btn(`${routeIdentity(route)}<span class="key-route-chevron" aria-hidden="true">⌄</span>`,'key-route-dropdown','key-route-control',`${attrs(k.id)} aria-label="更换绑定线路：${esc(route?.name||'线路已删除')}" aria-expanded="${c.keyRouteOpen===k.id}"`)}${keyRouteMenu(c,k)}</div>`,
   `<strong class="data">${k.enabled?k.concurrency:0} / ${s.concurrency}</strong>`,
   `<span class="data">今日 ${money(M.summarize(today).cost)}</span><span class="cell-sub">30天 ${money(M.summarize(usage).cost)}</span>`,
   k.expires?esc(k.expires):'永久有效',
   `<div class="key-actions">${btn('使用密钥','use-key','text-btn',attrs(k.id))}${btn('导入 CCS','import-key','text-btn',attrs(k.id))}${btn(k.enabled?'禁用':'启用','toggle-key',k.enabled?'text-btn warning':'text-btn',attrs(k.id))}${btn('编辑','edit-key','text-btn',attrs(k.id))}${btn('删除','delete-key','text-btn danger',attrs(k.id))}</div>`,
   ...extraKeyCells(k,usage)
  ];
 });
 const first=allRows.length?start+1:0,last=allRows.length?start+rows.length:0;
 const pagination=`<div class="key-pagination-bar"><span>显示 ${first} 至 ${last} 共 ${allRows.length} 条结果</span><label class="key-page-size"><span>每页数量</span>${select('每页数量',pageSize,[[10,'10'],[20,'20'],[50,'50']],'data-change="key-page-size"')}</label><div class="key-pagination" aria-label="密钥分页">${btn('‹','key-page','page-button',`data-delta="-1" aria-label="上一页" ${currentPage===1?'disabled':''}`)}<span class="page-current" aria-current="page">${currentPage}</span>${btn('›','key-page','page-button',`data-delta="1" aria-label="下一页" ${currentPage===totalPages?'disabled':''}`)}</div></div>`;
 return `<section aria-label="我的密钥"><div class="toolbar">${btn('刷新','refresh')}${btn('列设置','columns','','data-table="keys"')}${btn('创建密钥','create-key','primary')}</div><div class="filters"><input type="search" aria-label="搜索名称或Key" placeholder="搜索名称或Key..." value="${esc(c.keyFilter.search)}" data-input="key-search">${select('线路筛选',c.keyFilter.route,[['','全部线路'],...s.routes.map(r=>[r.id,r.name])],'data-change="key-filter" data-field="route"')}${select('状态筛选',c.keyFilter.status,[['','全部状态'],['enabled','启用'],['disabled','已禁用'],['expired','已过期']],'data-change="key-filter" data-field="status"')}${c.keyFilter.route||c.keyFilter.search||c.keyFilter.status?btn('清除筛选','clear-keys','ghost'):''}</div><section class="panel surface endpoint"><div><small>API 端点 <span class="badge success">默认</span></small><code>${M.endpoint}</code></div><div class="row">${btn('复制地址','copy-endpoint')}${btn('接入说明','use-key')}</div></section><section class="panel"><div class="panel-head"><h3>API 密钥</h3><small>密钥默认脱敏展示；可点击线路名称或编辑按钮更换绑定线路</small></div>${table(headers.filter((_,i)=>!hidden.includes(i)),data.map(row=>row.filter((_,i)=>!hidden.includes(i))),'key-table',keyHeaders.filter((_,i)=>!hidden.includes(i)))}${allRows.length?'':empty(s.keys.length?'没有匹配的密钥':'暂无 API 密钥',btn(s.keys.length?'清除筛选':'创建密钥',s.keys.length?'clear-keys':'create-key','primary'))}${pagination}</section></section>`;
}
export function usageRows(c){let rows=M.filterUsage(c.state,c.usageFilter);const [field,dir]=c.usageSort;return rows.sort((a,b)=>(typeof a[field]==='number'?a[field]-b[field]:String(a[field]).localeCompare(String(b[field])))*dir);}
export function usageValues(r){return [r.keyName,r.model,r.reasoning,r.endpoint,r.ip+(r.region?' · '+r.region:''),r.routeName,M.usageTypeLabels[r.type]||r.type,M.usageModeLabels[r.mode]||r.mode,r.input+r.output+r.cache,r.cost,r.latency,date(r.time)];}
function chart(c,title,field){const metric=c.chartMetric[field]||'tokens',rows=usageRows(c),items=M.distribution(rows,field,metric),total=items.reduce((n,x)=>n+x[1],0),shown=items.length>3?[...items.slice(0,2),['其他',items.slice(2).reduce((n,x)=>n+x[1],0)]]:items;return `<section class="chart"><div class="chart-head"><h3>${title}</h3>${segments(field,metric)}</div>${items.length?shown.map(([label,value])=>`<div class="bar-row"><span title="${esc(label)}">${esc(label)} ${Math.round(total?value/total*100:0)}%</span><div class="bar-track"><span style="width:${total?value/total*100:0}%"></span></div></div>`).join(''):empty('暂无数据')}</section>`;}
const segments=(id,metric)=>`<div class="segment">${btn('按 Token','chart-metric',metric==='tokens'?'active':'',`data-chart="${id}" data-metric="tokens"`)}${btn('按实际消费','chart-metric',metric==='cost'?'active':'',`data-chart="${id}" data-metric="cost"`)}</div>`;
export const usageErrorHeaders=['Key 名称','模型','端点','IP','类型','分类','错误信息','时间','User Agent','详情'];
function usageDatePicker(c){const f=c.usageFilter,d=c.usageDateDraft||f;return `<div class="usage-date-picker">${btn(esc(M.usageDateLabel(f)),'usage-date-toggle','',`aria-expanded="${!!c.usageDateOpen}" aria-label="时间范围"`)}${c.usageDateOpen?`<div class="usage-date-popover"><div class="usage-date-presets">${M.usageDatePresets.map(([id,label])=>btn(label,'usage-date-preset',M.usageDateRange(id).startDate===d.startDate&&M.usageDateRange(id).endDate===d.endDate?'active':'',`data-preset="${id}" aria-pressed="${M.usageDateRange(id).startDate===d.startDate&&M.usageDateRange(id).endDate===d.endDate}"`)).join('')}</div>${field('开始日期',`<input type="date" aria-label="开始日期" data-change="usage-date" data-field="startDate" value="${esc(d.startDate)}" max="${esc(d.endDate)}">`)}${field('结束日期',`<input type="date" aria-label="结束日期" data-change="usage-date" data-field="endDate" value="${esc(d.endDate)}" min="${esc(d.startDate)}">`)}${btn('应用','usage-date-apply','primary')}</div>`:''}</div>`;}
function usagePage(c){
 const s=c.state,rows=usageRows(c),a=M.summarize(rows),f=c.usageFilter,hidden=s.columns.usage||[],errors=s.allowUserViewErrorRequests&&c.usageTab==='errors',ef=c.usageErrorFilter||{},errorRows=M.filterUsageErrors(s,{...ef,startDate:f.startDate,endDate:f.endDate}),shown=errors?errorRows.sort((a,b)=>{const [key,dir]=c.usageErrorSort||['time',-1];return (typeof a[key]==='number'?a[key]-b[key]:String(a[key]).localeCompare(String(b[key])))*dir;}):rows,pageSize=c.usagePageSize||20,totalPages=Math.max(1,Math.ceil(shown.length/pageSize)),statsError=c.requestErrors?.usageStats,listError=c.requestErrors?.[errors?'usageErrors':'usageList'];c.usagePage=Math.min(Math.max(1,c.usagePage),totalPages);
 const filters=errors?[['key','Key 名称','全部 Key',s.keys.map(k=>[k.id,k.name])],['category','分类','全部分类',Object.entries(M.usageErrorLabels)]]:[['key','API 密钥','全部密钥',s.keys.map(k=>[k.id,k.name])],['model','模型','全部模型',[...new Set(s.usage.map(r=>r.model))]],['route','线路','全部线路',s.routes.map(r=>[r.id,r.name])],['mode','计费模式','全部计费模式',Object.entries(M.usageModeLabels)]];
 const data=shown.slice((c.usagePage-1)*pageSize,c.usagePage*pageSize).map(r=>errors?[esc(r.keyName),esc(r.model),esc(r.endpoint),esc((r.ip||'—')+(r.region?' · '+r.region:'')),esc(M.usageTypeLabels[r.type]||'—'),esc(M.usageErrorLabels[r.category]||r.category),esc(r.message),date(r.time),esc(r.userAgent||'—'),btn('查看','usage-error-detail','text-btn',attrs(r.id))]:[...usageValues(r).map((x,i)=>i===8?compact(x):i===9?money(x):i===10?Number(x).toFixed(2)+'s':esc(x)),btn('查看','request-detail','text-btn',attrs(r.id))]);
 const statsWork=statsError?requestError('用量统计暂时不可用',statsError.message,'retry-usage-stats'):`<div class="stats">${[['总请求数',num(a.requests),'所选范围内'],['总 Token',compact(a.tokens),`输入 ${compact(a.input)} · 输出 ${compact(a.output)} · 缓存 ${compact(a.cache)}`],['总消费',money(a.cost),'标准价 '+money(a.standard)],['平均耗时',a.latency===null?'—':a.latency.toFixed(2)+'s','当前筛选范围']].map(([title,value,sub])=>`<div class="stat"><span class="muted">${title}</span><div class="value data" data-stat="${title}">${value}</div><small>${sub}${title==='总 Token'?btn('ⓘ','cache-info','text-btn','aria-label="缓存 Token 说明"'):''}</small></div>`).join('')}</div>`;
 const chartsWork=statsError?'':`<div class="charts">${chart(c,'模型分布','model')}${chart(c,'线路使用分布','routeName')}${chart(c,'端点分布','endpoint')}<section class="chart"><div class="chart-head"><h3>Token 使用趋势</h3></div>${rows.length?`<div class="trend"><div><strong class="data">${compact(a.tokens)}</strong><small class="cell-sub">${c.granularity==='hour'?'按小时':'按天'} · 当前筛选范围</small></div><canvas id="trend" aria-label="当前筛选范围的 Token 趋势"></canvas></div>`:empty('暂无数据')}</section></div>`;
 const detailWork=listError?requestError(errors?'错误请求暂时不可用':'使用记录暂时不可用',listError.message,errors?'retry-usage-errors':'retry-usage-list'):`${errors?table(usageErrorHeaders.map((h,i)=>i===1||i===7?btn(h+' ↕','usage-error-sort','sort',`data-field="${i===1?'model':'time'}"`):h).filter((_,i)=>!(s.columns.usageErrors||[8]).includes(i)),data.map(r=>r.filter((_,i)=>!(s.columns.usageErrors||[8]).includes(i))),'usage-table'):table(usageHeaders.map((h,i)=>i===1||i===11?btn(h+' ↕','usage-sort','sort',`data-field="${i===1?'model':'time'}"`):h).filter((_,i)=>!hidden.includes(i)),data.map(r=>r.filter((_,i)=>!hidden.includes(i))),'usage-table')}${shown.length?'':empty(errors?'暂无错误请求':'暂无数据')}<div class="table-footer"><span>共 ${shown.length} 条 · 第 ${c.usagePage} / ${totalPages} 页</span>${select('每页数量',pageSize,[[10,'10 条/页'],[20,'20 条/页'],[50,'50 条/页'],[100,'100 条/页']],'data-change="usage-page-size"')}<div class="pagination">${btn('上一页','usage-page','small',`data-delta="-1" ${c.usagePage===1?'disabled':''}`)}${btn('下一页','usage-page','small',`data-delta="1" ${c.usagePage===totalPages?'disabled':''}`)}</div></div>`;
 return `<section aria-label="使用记录">
 <section class="usage-overview" aria-label="用量概览"><div class="time-toolbar"><div class="usage-time-control"><span>时间范围</span>${usageDatePicker(c)}</div><div class="usage-time-control"><span>统计粒度</span>${select('统计粒度',c.granularity,[['hour','按小时'],['day','按天']],'data-change="granularity"')}</div></div>${statsWork}</section>
 ${statsError?'':`<section class="usage-analysis" aria-label="使用分析">${chartsWork}</section>`}
 <section class="usage-records" aria-label="请求记录">${s.allowUserViewErrorRequests?`<div class="tabs" role="tablist">${[['usage','用量明细'],['errors','错误请求']].map(([id,label])=>btn(label,'usage-tab',errors===(id==='errors')?'active':'',`data-tab="${id}" role="tab" aria-selected="${errors===(id==='errors')}"`)).join('')}</div>`:''}
 <div class="filters usage-filters">${filters.map(([id,label,all,options])=>field(label,select(label,(errors?ef:f)[id]||'',[['',all],...options],`data-change="${errors?'usage-error-filter':'usage-filter'}" data-field="${id}"`))).join('')}${errors?field('模型',`<input type="search" aria-label="错误模型" placeholder="搜索模型" data-change="usage-error-filter" data-field="model" value="${esc(ef.model||'')}">`):''}</div>
 <div class="toolbar">${btn('刷新','apply-usage')}${btn('重置','reset-usage')}${btn('列设置','columns','',`data-table="${errors?'usageErrors':'usage'}"`)}${errors?'':btn('导出 CSV','export-csv')}</div>
 <div class="usage-detail"><div class="panel-head"><h3>${errors?'错误请求':'请求明细'}</h3>${btn(c.geoLoading?'地区查询中…':'批量获取地区',errors?'error-regions':'regions','small',!shown.length||listError||c.geoLoading?'disabled':'')}</div>${detailWork}</div></section></section>`;
}
const rights=s=>`<section class="entitlements" aria-label="账户权益"><div class="entitlement-title"><h2>账户权益</h2><small>当前账户状态</small></div><div class="balances"><div class="balance-stat"><small>可用额度</small><strong class="data">${money(s.balance)}</strong></div><div class="balance-stat"><small>并发上限</small><strong class="data">${s.concurrency}<span> 路</span></strong></div></div></section>`;
function paymentHandoff(c){
 const flow=c.paymentFlow;
 if(!flow)return '';
 const expires=flow.expiresAt?date(flow.expiresAt):'以支付页面为准';
 return `<section class="native-payment-panel" aria-label="原生支付承接">
  <div class="payment-handoff-head"><div><span class="badge">sub 原生支付承接</span><h2>等待支付</h2><p>订单已创建。生产环境会按渠道进入二维码、弹窗或跳转支付，并持续轮询订单状态。</p></div><div class="payment-channel"><span class="payment-mark">支</span><div><small>支付方式</small><strong>支付宝</strong></div></div></div>
  <div class="payment-handoff-grid">
   <div class="demo-payment-qr" aria-label="支付二维码演示占位"><span>支付承接</span><strong>演示不生成真实二维码</strong><small>生产环境由 sub 返回的渠道信息渲染</small></div>
   <div class="payment-order-summary"><span class="summary-label">应付金额</span><strong class="payment-due data">${rmb(flow.payAmount??flow.amount)}</strong><dl><dt>订单编号</dt><dd class="data">${esc(flow.orderNumber)}</dd><dt>充值额度</dt><dd>${money(flow.amount)}</dd><dt>有效期</dt><dd>${esc(expires)}</dd></dl><p class="notice">原生流程会保存恢复快照；刷新或返回后可继续查询待支付订单。当前原型不会打开真实支付渠道。</p></div>
  </div>
  <footer class="payment-handoff-actions">${btn('取消订单','cancel-payment-order','ghost danger',attrs(flow.orderId))}${btn('查看我的订单','go-orders')}${btn('打开支付窗口','open-native-payment','primary')}</footer>
 </section>`;
}
function rechargeChoice(c){return `<section class="recharge-panel"><div class="recharge-choice"><div class="recharge-section-head"><span class="section-index">01</span><div><h3>选择充值额度</h3><p>最低充值额度 $1，充值后计入账户可用额度</p></div></div><div class="amounts">${[10,30,50,100,200].map(n=>btn('$'+n,'amount',c.amount===n?'selected':'',`data-amount="${n}" aria-pressed="${c.amount===n}"`)).join('')}</div>${field('自定义额度',`<input class="amount-input" type="number" min="1" max="10000" step="0.01" placeholder="输入充值额度（USD）" aria-label="自定义充值额度" data-input="amount" value="${c.customAmount?esc(c.amount):''}">`)}<div class="recharge-divider"></div><div class="recharge-section-head compact"><span class="section-index">02</span><div><h3>支付方式</h3><p>选择本次充值使用的支付渠道</p></div></div><div class="payment-method selected"><span class="payment-mark">支</span><div><strong>支付宝</strong><small>当前可用</small></div><span class="payment-check" aria-label="已选择">✓</span></div></div><aside class="payment-summary" aria-label="金额核对"><div><span class="summary-label">本次支付</span><h3>金额核对</h3></div><div class="summary-lines"><div><span>充值额度</span><strong id="credit-preview">${money(c.amount)}</strong></div><div class="summary-total"><span>实际支付</span><strong id="payment-preview">${rmb(c.amount)}</strong></div></div>${c.paymentError?`<div class="payment-create-error" role="alert"><strong>订单未创建</strong><span>${esc(c.paymentError)}</span></div>`:''}${btn('创建订单 '+rmb(c.amount),'pay','primary pay','id="pay-button"')}<p class="footnote">订单创建后由 sub 原生支付流程承接；演示不发起真实支付</p></aside></section>`;}
function redeemPanel(s){return `<section class="redeem-panel"><div class="recharge-section-head"><span class="section-index">01</span><div><h3>输入兑换码</h3><p>请输入完整兑换码，字母不区分大小写</p></div></div><form id="redeem-form" class="redeem-form"><input name="code" aria-label="兑换码" placeholder="输入兑换码" required autocomplete="off"><button class="primary" type="submit">确认兑换</button></form><div id="redeem-error" class="inline-error" role="alert"></div><small class="cell-sub">体验兑换码：DEMO30（额度）或 PLUS2（并发），每个仅可使用一次。</small><div class="redeem-history"><h3>近 30 天兑换记录</h3>${table(['兑换时间','兑换码结果','获得额度或权益','处理状态'],s.redemptions.filter(r=>r.created>Date.now()-30*86400000).map(r=>[date(r.created),esc(r.code),`<strong class="data">${esc(r.reward)}</strong>`,'<span class="success">兑换成功</span>']))}${s.redemptions.length?'':empty('近 30 天暂无兑换记录')}</div></section>`;}
function rechargePage(c){
 const s=c.state;
 if(c.paymentFlow)return `<section class="recharge-page" aria-label="充值与兑换">${rights(s)}<div class="payment-page-link">${btn('我的订单 →','go-orders','order-link')}</div>${paymentHandoff(c)}</section>`;
 return `<section class="recharge-page" aria-label="充值与兑换">${rights(s)}<div class="recharge-nav"><div class="tabs" role="tablist">${btn('充值','recharge-tab',c.rechargeTab==='recharge'?'active':'','data-tab="recharge" role="tab" aria-selected="'+(c.rechargeTab==='recharge')+'"')}${btn('兑换码','recharge-tab',c.rechargeTab==='redeem'?'active':'','data-tab="redeem" role="tab" aria-selected="'+(c.rechargeTab==='redeem')+'"')}</div>${btn('我的订单 →','navigate','order-link','data-page="orders"')}</div>${c.rechargeTab==='recharge'?rechargeChoice(c):redeemPanel(s)}</section>`;
}
const orderStatusMeta={
 pending:{filter:'pending',label:'待支付',kind:'warning'},
 paid:{filter:'completed',label:'已完成',kind:'success'},
 recharging:{filter:'',label:'充值中',kind:'warning'},
 completed:{filter:'completed',label:'已完成',kind:'success'},
 failed:{filter:'failed',label:'失败',kind:'danger'},
 expired:{filter:'',label:'已过期',kind:'muted'},
 closed:{filter:'',label:'已取消',kind:'muted'},
 cancelled:{filter:'',label:'已取消',kind:'muted'},
 refund_requested:{filter:'',label:'退款申请中',kind:'warning'},
 refunding:{filter:'',label:'退款中',kind:'warning'},
 refund_pending:{filter:'',label:'退款待处理',kind:'warning'},
 partially_refunded:{filter:'',label:'部分退款',kind:'warning'},
 refunded:{filter:'refunded',label:'已退款',kind:'success'},
 refund_failed:{filter:'',label:'退款失败',kind:'danger'}
};
const statusMeta=o=>orderStatusMeta[String(o.status||'').toLowerCase()]||{filter:'failed',label:String(o.status||'未知状态'),kind:'muted'};
function ordersPage(c){
 const rows=c.state.orders.filter(o=>!c.orderFilter||statusMeta(o).filter===c.orderFilter);
 return `<section aria-label="我的订单"><div class="orders-heading">${btn('← 返回充值与兑换','navigate','ghost','data-page="recharge"')}</div><div class="filters"><span class="label" style="margin:0">订单状态</span>${select('订单状态',c.orderFilter,[['','全部状态'],['pending','待支付'],['completed','已完成'],['failed','失败'],['refunded','已退款']],'data-change="order-filter"')}${btn('刷新','refresh','push')}</div><section class="panel"><h3>订单列表</h3>${table(['订单 ID','订单编号','支付金额','获得总额度','充值额度','赠送额度','支付方式','状态','创建时间','操作'],rows.map(o=>{const status=statusMeta(o),completed=status.filter==='completed';return [esc(o.id.slice(0,8)),btn(esc(o.number),'order-detail','text-btn',attrs(o.id)),`<strong>${rmb(o.amount)}</strong>`,`<strong>${money(completed?o.credit:0)}</strong>`,money(o.amount),money(o.bonus),o.method,`<span class="${status.kind}">${esc(status.label)}</span>`,date(o.created),status.filter==='pending'?btn('取消订单','cancel-order','text-btn danger',attrs(o.id)):btn('查看详情','order-detail','text-btn',attrs(o.id))];}),'orders-table')}${rows.length?'':empty('暂无订单')}</section></section>`;
}
function profilePage(c){const s=c.state,p=s.profile;return `<section aria-label="个人资料"><section class="panel surface profile-panel"><h2>账户信息与权益</h2><div class="profile-overview"><div><span class="avatar big">${p.avatar?`<img src="${esc(p.avatar)}" alt="当前头像">`:esc(p.name.slice(0,1))}</span>${btn('更换头像','avatar','small','style="margin-top:8px"')}</div><div><small>用户名</small><div class="name">${esc(p.name)}</div>${btn('编辑','edit-profile','small','data-field="name"')}</div><div><small>当前可用额度</small><div class="big-num data">${money(s.balance)}</div></div><div><small>当前并发上限</small><div class="big-num data">${s.concurrency} 路</div></div><div><small>登录邮箱</small><div>${esc(p.email)}</div><small class="success">已绑定</small></div></div></section><section class="panel profile-panel"><h3>登录邮箱</h3><p class="description">当前邮箱用于登录和账户通知</p><div class="profile-row"><strong>${esc(p.email)}</strong><span class="success small-text">已验证</span>${btn('管理邮箱','edit-profile','','data-field="email"')}</div><p class="hint">更换邮箱时需要邮箱验证码和身份验证</p></section><section class="panel profile-panel"><h3>账户安全</h3><div class="profile-row"><strong>登录密码</strong><span class="${p.passwordSet?'success':'muted'}">${p.passwordSet?'已设置':'未设置'}</span>${btn(p.passwordSet?'修改密码':'设置密码','edit-profile','','data-field="password"')}</div><div class="spacer" style="max-width:670px"></div><div class="profile-row"><strong>两步验证</strong><span class="${p.twoFactor?'success':'muted'}">${p.twoFactor?'已开启':'未开启'}</span>${btn(p.twoFactor?'管理':'设置','twofactor')}</div><div class="spacer" style="max-width:670px"></div><div class="profile-row"><strong>Passkey</strong>${s.passkeyEnabled===true?`<span class="${p.passkeys.length?'success':'muted'}">${p.passkeys.length?p.passkeys.length+' 个已添加':'未添加'}</span>${btn(p.passkeys.length?'管理':'添加','passkey')}`:`<span class="muted">管理员未启用</span>${btn('未启用','passkey','', 'disabled aria-disabled="true" title="管理员在后台启用 Passkey 后可用"')}`}</div></section><section class="panel profile-panel"><h3>额度提醒</h3><p class="description">当可用额度低于阈值时发送提醒</p><form id="threshold-form"><div class="threshold">${field('提醒阈值（USD）',`<input name="threshold" type="number" min="0" step="0.01" value="${p.threshold}" required>`)}</div><button type="submit" class="primary">保存设置</button></form></section><section class="panel surface"><h3>客服支持</h3><p class="secondary" style="margin:16px 0">遇到线路配置、充值或账户问题时，可联系星桥客服。</p>${btn('联系客服','support')}</section></section>`;}
export function drawTrend(c){const canvas=document.querySelector('#trend');if(!canvas)return;const rows=usageRows(c),metric='tokens';const values=new Map();for(const r of rows){const localBucket=new Date(r.time);if(c.granularity==='hour')localBucket.setMinutes(0,0,0);else localBucket.setHours(0,0,0,0);const t=localBucket.getTime();values.set(t,(values.get(t)||0)+(metric==='cost'?r.cost:r.input+r.output+r.cache));}const pts=[...values.entries()].sort((a,b)=>a[0]-b[0]);const w=canvas.clientWidth,h=86,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#61C9D9';ctx.lineWidth=1.5;ctx.beginPath();const max=Math.max(...pts.map(p=>p[1]),1);pts.forEach((p,i)=>{const x=6+i/Math.max(pts.length-1,1)*(w-12),y=h-12-(p[1]/max)*(h-24);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();if(pts.length===1){ctx.beginPath();ctx.arc(6,h-12-pts[0][1]/max*(h-24),3,0,Math.PI*2);ctx.fillStyle='#61C9D9';ctx.fill();}}
